# Generated by Django 2.0 on 2020-05-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_auto_20200506_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='textnote',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
