# Generated by Django 2.0 on 2020-05-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_todopoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='todopoints',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoapp.Status'),
        ),
    ]
