# Generated by Django 2.0 on 2020-06-01 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0010_auto_20200526_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_connect', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoapp.Status')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_connect', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
