# Generated by Django 2.0 on 2020-06-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0012_todoaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
